Neos:
  Flow:
    mvc:
      routes:
        'PunktDe.SiteSpecifics':
          position: 'before Neos.Neos'

  Neos:
    Ui:
      configurationDefaultEelContext:
        PunktDe.SiteSpecifics.SiteSpecificContentDimensions: \PunktDe\SiteSpecifics\Eel\SiteSpecificContentDimensionsHelper

      initialState:
        cr:
          contentDimensions:
            byName: '${PunktDe.SiteSpecifics.SiteSpecificContentDimensions.contentDimensionsByNameForSite(site)}'
            allowedPresets: '${Neos.Ui.Api.emptyArrayToObject(PunktDe.SiteSpecifics.SiteSpecificContentDimensions.allowedPresetsByNameForSite(documentNode.context.dimensions, site))}'
