#PunktDe:
#  SiteSpecifics:
#    mySite:
#      nodeTypes:
#        'Vendor.Package:Content.NodeType':
#          ui:
#            group: not-shown

#      dimensionSelector:
#        country:
#          language:
#            de: ~
