--
#PunktDe:
#  SiteSpecifics:
#    mySite:
#      nodeTypes:
#        'Vendor.Package:Content.NodeType':
#          ui:
#            group: not-shown

#      dimensionSelector:
#        language:
#          presets:
#            de: ~

#        country:
#          presets:
#            deu:
#              constraints:
#                language:
#                  'en': false
